In [24]:
import numpy as np
A=np.array([[5,-4,0],[9,7,6],[0,2,5]])

def eliminate(r1, r2, col, target=0):
    fac = (r2[col]-target) / r1[col]
    for i in range(len(r2)):
        r2[i] -= fac * r1[i]

def gauss(a):
    for i in range(len(a)):
        if a[i][i] == 0:
            for j in range(i+1, len(a)):
                if a[i][j] != 0:
                    a[i], a[j] = a[j], a[i]
                    break
            else:
                raise ValueError("La matriz no es invertible")
        for j in range(i+1, len(a)):
            eliminate(a[i], a[j], i)
    for i in range(len(a)-1, -1, -1):
        for j in range(i-1, -1, -1):
            eliminate(a[i], a[j], i)
    for i in range(len(a)):
        eliminate(a[i], a[i], i, target=1)
    return a

def inverse(a):
    tmp = [[] for _ in a]
    for i,row in enumerate(a):
        assert len(row) == len(a)
        tmp[i].extend(list(row) + [0]*i + [1] + [0]*(len(a)-i-1))
    gauss(tmp)
    ret = []
    for i in range(len(tmp)):
        ret.append(tmp[i][len(tmp[i])//2:])
    return ret

print(np.array(inverse(A)))

[[ 0.0779661   0.06779661 -0.08135593]
 [-0.15254237  0.08474576 -0.10169492]
 [ 0.06101695 -0.03389831  0.24067797]]


In [25]:
np.linalg.inv(A)

array([[ 0.0779661 ,  0.06779661, -0.08135593],
       [-0.15254237,  0.08474576, -0.10169492],
       [ 0.06101695, -0.03389831,  0.24067797]])