## Today:
* Pandas - continuation (downloading from repositories, .to_numpy)
* Dictionaries - extracting data
* .MAT files
* os library

## Pandas - cont..

In [96]:
import pandas as pd
#url = "https://gitlab.com/mirsakhawathossain/pha-ml/-/raw/master/Dataset/dataset.csv"
df = pd.read_csv('dataset.csv')
df.head()

/usr/lib64/python3.7/site-packages/IPython/core/interactiveshell.py:3156: DtypeWarning: Columns (3,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


id    spkid       full_name pdes     name prefix neo pha     H  \
0  a0000001  2000001         1 Ceres    1    Ceres    NaN   N   N  3.40   
1  a0000002  2000002        2 Pallas    2   Pallas    NaN   N   N  4.20   
2  a0000003  2000003          3 Juno    3     Juno    NaN   N   N  5.33   
3  a0000004  2000004         4 Vesta    4    Vesta    NaN   N   N  3.00   
4  a0000005  2000005       5 Astraea    5  Astraea    NaN   N   N  6.90   

   diameter  ...       sigma_i      sigma_om       sigma_w      sigma_ma  \
0   939.400  ...  4.608900e-09  6.168800e-08  6.624800e-08  7.820700e-09   
1   545.000  ...  3.469400e-06  6.272400e-06  9.128200e-06  8.859100e-06   
2   246.596  ...  3.223100e-06  1.664600e-05  1.772100e-05  8.110400e-06   
3   525.400  ...  2.170600e-07  3.880800e-07  1.789300e-07  1.206800e-06   
4   106.699  ...  2.740800e-06  2.894900e-05  2.984200e-05  8.303800e-06   

       sigma_ad       sigma_n      sigma_tp     sigma_per  class      rms  
0  1.111300e-11  1.196500e-12  3.782900e-08  9.415900e-09    MBA  0.43301  
1  4.961300e-09  4.653600e-10  4.078700e-05  3.680700e-06    MBA  0.35936  
2  4.363900e-09  4.413400e-10  3.528800e-05  3.107200e-06    MBA  0.33848  
3  1.648600e-09  2.612500e-10  4.103700e-06  1.274900e-06    MBA  0.39980  
4  4.729000e-09  5.522700e-10  3.474300e-05  3.490500e-06    MBA  0.52191  

[5 rows x 45 columns]

In [97]:
# how to delete columns that names contain word "sigma"
df2=df[df.columns.drop(list(df.filter(regex='sigma')))]

In [98]:
df2_np = df2.to_numpy()
df2_np[0:10,2:3]

array([['     1 Ceres'],
       ['     2 Pallas'],
       ['     3 Juno'],
       ['     4 Vesta'],
       ['     5 Astraea'],
       ['     6 Hebe'],
       ['     7 Iris'],
       ['     8 Flora'],
       ['     9 Metis'],
       ['    10 Hygiea']], dtype=object)

## Dictionaries

In [99]:
from sklearn import datasets
iris = datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [100]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [101]:
print(type(iris['data']))

<class 'numpy.ndarray'>


In [102]:
iris['data'][0:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [103]:
iris['data'].shape

(150, 4)

In [104]:
import numpy as np
rand_num = np.random.randint(0,iris['data'].shape[0],3)
print(rand_num)

[ 88 111  85]


In [105]:
iris['data'][rand_num]

array([[5.6, 3. , 4.1, 1.3],
       [6.4, 2.7, 5.3, 1.9],
       [6. , 3.4, 4.5, 1.6]])

In [106]:
iris['target'][rand_num]

array([1, 2, 1])

# .MAT files 

In [107]:
! ls data.mat

data.mat


In [108]:
import scipy.io

In [109]:
data_dict = scipy.io.loadmat('data.mat')

In [110]:
print(type(data_dict))

<class 'dict'>


In [111]:
data_dict.keys()

dict_keys(['__header__', '__version__', '__globals__', 'X', 'y'])

In [112]:
data_dict['X'].shape

(32, 32, 3, 26032)

## Python and operating system

In [113]:
! ls flowers/

100080576_f52e8ee070_n.jpg    105806915_a9c13e2106_n.jpg
10140303196_b88d3d6cec.jpg    10712722853_5632165b04.jpg
10172379554_b296050f82_n.jpg  107592979_aaa9cdfe78_m.jpg
10172567486_2748826a8b.jpg    10770585085_4742b9dac3_n.jpg
10172636503_21bededa75_n.jpg  10841136265_af473efc60.jpg
102841525_bd6628ae3c.jpg      10993710036_2033222c91.jpg
1031799732_e7f4008c03.jpg     10993818044_4c19b86c82.jpg
10391248763_1d16681106_n.jpg  10994032453_ac7f8d9e2e.jpg
10437754174_22ec990b77_m.jpg  11023214096_b5b39fab08.jpg
10437770546_8bb6f7bdd3_m.jpg  11023272144_fce94401f2_m.jpg
10437929963_bc13eebe0c.jpg    F0000MTH.CSV
10466290366_cc72e33532.jpg    F0000TEK.JPG
10466558316_a7198b87e2.jpg    F0000TEK.SET
10555749515_13a12a026e.jpg    F0001MTH.CSV
10555815624_dc211569b0.jpg    F0001TEK.JPG
10555826524_423eb8bf71_n.jpg  F0001TEK.SET
10559679065_50d2b16f6d.jpg


In [114]:
import os, fnmatch

for filename in os.listdir('flowers/'):
    if fnmatch.fnmatch(filename,'*.jpg'):
        print(filename)

10994032453_ac7f8d9e2e.jpg
10555749515_13a12a026e.jpg
10466290366_cc72e33532.jpg
100080576_f52e8ee070_n.jpg
107592979_aaa9cdfe78_m.jpg
1031799732_e7f4008c03.jpg
10712722853_5632165b04.jpg
10993818044_4c19b86c82.jpg
10437929963_bc13eebe0c.jpg
10993710036_2033222c91.jpg
10437770546_8bb6f7bdd3_m.jpg
105806915_a9c13e2106_n.jpg
102841525_bd6628ae3c.jpg
10172567486_2748826a8b.jpg
10437754174_22ec990b77_m.jpg
10555826524_423eb8bf71_n.jpg
10140303196_b88d3d6cec.jpg
10172636503_21bededa75_n.jpg
10466558316_a7198b87e2.jpg
10770585085_4742b9dac3_n.jpg
11023214096_b5b39fab08.jpg
11023272144_fce94401f2_m.jpg
10559679065_50d2b16f6d.jpg
10172379554_b296050f82_n.jpg
10841136265_af473efc60.jpg
10391248763_1d16681106_n.jpg
10555815624_dc211569b0.jpg


In [115]:
!pwd

/home/michal/MEGASyncWork/Universidad_de_Antioquia/CARGAS/Carga_6_Diplomado_en_Big_Data/Materials/python_tools_quick


In [116]:
df_all=pd.DataFrame()
for dirName, dirList, fileList in os.walk('FFT'):
    for fname in fileList:
        if fnmatch.fnmatch(fname,'*.CSV'):
            fullFilename = os.path.join(dirName+'/'+fname)
            df = pd.read_csv(fullFilename,skiprows=18)
            cols = [0,1,2,3,5]
            df.drop(df.columns[cols], axis=1, inplace=True)
            df_all=pd.concat([df_all,df],axis=1)

In [117]:
df_all.head()

-93.74850   -88.54850   -82.94850  -100.96910   -58.16910   -66.16910  \
0    -94.9485    -86.1485    -84.9485    -92.9691    -58.9691    -62.5691   
1    -88.9485    -84.9485    -85.7485    -91.7691    -67.7691    -66.9691   
2    -85.3485    -85.7485    -79.7485    -89.3691    -71.3691    -66.9691   
3    -88.9485    -90.9485    -81.7485    -88.9691    -62.1691    -59.7691   
4    -87.7485    -93.7485    -86.9485    -92.9691    -63.7691    -57.7691   

    -62.16910   -96.96910   -94.94850   -86.94850  ...   -90.94850  \
0    -55.7691    -90.9691    -86.1485    -90.9485  ...    -94.9485   
1    -60.5691    -89.7691    -83.7485    -87.7485  ...    -89.7485   
2    -57.7691    -97.7691    -86.9485    -90.9485  ...    -83.7485   
3    -57.3691    -92.1691    -86.9485    -88.5485  ...    -86.9485   
4    -65.3691    -89.7691    -83.7485    -91.3485  ...    -91.7485   

    -80.54850   -52.58970   -52.18970   -45.38970   -52.18970   -57.38970  \
0    -81.7485    -57.3897    -54.9897    -54.5897    -53.3897    -58.1897   
1    -86.9485    -55.7897    -60.9897    -52.9897    -57.7897    -58.1897   
2    -91.7485    -54.9897    -52.9897    -54.9897    -57.3897    -62.9897   
3    -90.9485    -55.7897    -58.9897    -46.9897    -63.7897    -53.7897   
4    -81.7485    -58.9897    -49.7897    -50.9897    -56.1897    -51.3897   

    -89.74850   -90.94850   -77.74850  
0    -82.9485    -86.9485    -83.3485  
1    -83.7485    -86.9485    -80.5485  
2    -84.9485    -89.7485    -93.7485  
3    -90.9485    -86.9485    -91.7485  
4    -83.7485    -88.5485    -82.9485  

[5 rows x 27 columns]

In [120]:
len(df_all.columns)

27

In [121]:
df_all.columns = [str(i) for i in range(len(df_all.columns))]

In [122]:
df_all.head()

0        1        2        3        4        5        6        7  \
0 -94.9485 -86.1485 -84.9485 -92.9691 -58.9691 -62.5691 -55.7691 -90.9691   
1 -88.9485 -84.9485 -85.7485 -91.7691 -67.7691 -66.9691 -60.5691 -89.7691   
2 -85.3485 -85.7485 -79.7485 -89.3691 -71.3691 -66.9691 -57.7691 -97.7691   
3 -88.9485 -90.9485 -81.7485 -88.9691 -62.1691 -59.7691 -57.3691 -92.1691   
4 -87.7485 -93.7485 -86.9485 -92.9691 -63.7691 -57.7691 -65.3691 -89.7691   

         8        9  ...       17       18       19       20       21  \
0 -86.1485 -90.9485  ... -94.9485 -81.7485 -57.3897 -54.9897 -54.5897   
1 -83.7485 -87.7485  ... -89.7485 -86.9485 -55.7897 -60.9897 -52.9897   
2 -86.9485 -90.9485  ... -83.7485 -91.7485 -54.9897 -52.9897 -54.9897   
3 -86.9485 -88.5485  ... -86.9485 -90.9485 -55.7897 -58.9897 -46.9897   
4 -83.7485 -91.3485  ... -91.7485 -81.7485 -58.9897 -49.7897 -50.9897   

        22       23       24       25       26  
0 -53.3897 -58.1897 -82.9485 -86.9485 -83.3485  
1 -57.7897 -58.1897 -83.7485 -86.9485 -80.5485  
2 -57.3897 -62.9897 -84.9485 -89.7485 -93.7485  
3 -63.7897 -53.7897 -90.9485 -86.9485 -91.7485  
4 -56.1897 -51.3897 -83.7485 -88.5485 -82.9485  

[5 rows x 27 columns]