##### HOMEWORK LINEAR ALGEBRA 3

Name: Shirley Maldonado.

Cc: 1004807437



Calculate  S5  using two methods. in a "for" loop and using diagonalization. Compare the results.


$$S=
\begin{bmatrix}
1 &  -1 & -1 & -1\\
-1 &  2 & 0 & 0\\
-1 &  3 & 3 & 0 \\
-1 &  0 & 1 & 4 \\
\end{bmatrix}$$


Usando un for

In [10]:
import numpy as np


In [30]:
S = np.array([[1,-1,-1,-1],
              [-1,2,0,0],
              [-1,3,3,0],
              [-1,0,1,4]])
k=S.shape
S5for=np.identity(k[0])

for i in range(5):
    S5for = np.matmul(S,S5for)
    
print("S^5 usando for: \n",S5for)

S^5 usando for: 
 [[  485.  -755.  -563.  -563.]
 [ -179.   280.   192.   192.]
 [ -675.  1201.   707.   464.]
 [-1027.  1448.  1275.  1518.]]


Usando la diagonalización

In [9]:
d, P = np.linalg.eig(S)

D = np.zeros(k)
for i in range(k[0]):
    D[i,i] = d[i]**5

P_1=np.linalg.inv(P)
sa=np.matmul(P, D) 
S5=np.matmul(sa, P_1)
    
print('S^5 usando diagonalización=\n',S5)

S^5=
 [[  485.  -755.  -563.  -563.]
 [ -179.   280.   192.   192.]
 [ -675.  1201.   707.   464.]
 [-1027.  1448.  1275.  1518.]]


##### Se puede ver que S^5 es igual usando un for o haciendolo usando la diagonal pues la diferencia entre las dos es casi 0.

In [32]:
print(S5for-S5)

[[-6.25277607e-13  7.95807864e-13  4.54747351e-13  3.41060513e-13]
 [-7.38964445e-13  1.19371180e-12  9.37916411e-13  9.37916411e-13]
 [-4.54747351e-13  6.82121026e-13  6.82121026e-13  1.13686838e-12]
 [ 1.13686838e-12 -1.13686838e-12 -6.82121026e-13 -6.82121026e-13]]
